<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['id' => 41, 'store_id' => 1, 'product_category_id' => 1, 'name' => 'YETI Rambler 30oz Tumbler with MagSlider Lid', 'slug' => 'yeti-rambler-30oz-tumbler', 'description' => 'Double-wall vacuum insulation keeps drinks cold for 7+ hours and hot for 3+ hours. Kitchen-grade stainless steel, BPA-free. Dishwasher safe. Perfect for coffee, beer, or water.', 'condition' => 'new', 'price' => 450000.00, 'weight' => 350, 'stock' => 25],
            ['id' => 42, 'store_id' => 1, 'product_category_id' => 1, 'name' => 'YETI Rambler 20oz Tumbler Stainless Steel', 'slug' => 'yeti-rambler-20oz-stainless', 'description' => 'Compact 20oz size perfect for commuting. DuraCoat color won\'t fade, peel, or crack. Fits most cupholders. Over-the-nose design for easy drinking.', 'condition' => 'new', 'price' => 380000.00, 'weight' => 280, 'stock' => 30],
            ['id' => 43, 'store_id' => 1, 'product_category_id' => 1, 'name' => 'YETI Rambler 10oz Lowball', 'slug' => 'yeti-rambler-10oz-lowball', 'description' => 'Perfect for whiskey on the rocks or morning espresso. Double-wall insulation keeps drinks at perfect temperature. Wide opening for easy pouring and cleaning.', 'condition' => 'new', 'price' => 320000.00, 'weight' => 200, 'stock' => 40],
            ['id' => 44, 'store_id' => 2, 'product_category_id' => 1, 'name' => 'YETI Rambler 26oz Bottle with Chug Cap', 'slug' => 'yeti-rambler-26oz-bottle', 'description' => 'Leak-proof Chug Cap with TripleHaul handle. Perfect for gym, hiking, or daily hydration. 18/8 stainless steel construction.', 'condition' => 'new', 'price' => 425000.00, 'weight' => 320, 'stock' => 20],
            ['id' => 45, 'store_id' => 2, 'product_category_id' => 1, 'name' => 'YETI Rambler 14oz Mug', 'slug' => 'yeti-rambler-14oz-mug', 'description' => 'Camp mug design with easy-grip handle. Keeps coffee hot from breakfast to lunch. Splash-resistant MagSlider lid included.', 'condition' => 'new', 'price' => 365000.00, 'weight' => 250, 'stock' => 35],

            ['id' => 46, 'store_id' => 2, 'product_category_id' => 2, 'name' => 'Hydro Flask 32oz Wide Mouth with Flex Cap', 'slug' => 'hydroflask-32oz-wide-mouth', 'description' => 'TempShield double-wall vacuum insulation. BPA-free and phthalate-free. Fits ice cubes perfectly. Color Last powder coat won\'t fade.', 'condition' => 'new', 'price' => 495000.00, 'weight' => 380, 'stock' => 28],
            ['id' => 47, 'store_id' => 2, 'product_category_id' => 2, 'name' => 'Hydro Flask 24oz Standard Mouth', 'slug' => 'hydroflask-24oz-standard-mouth', 'description' => 'Slim design fits most backpack pockets. Honeycomb insulation for superior temperature retention. Flex Cap is leakproof when closed.', 'condition' => 'new', 'price' => 425000.00, 'weight' => 300, 'stock' => 32],
            ['id' => 48, 'store_id' => 1, 'product_category_id' => 2, 'name' => 'Hydro Flask 20oz Tumbler', 'slug' => 'hydroflask-20oz-tumbler', 'description' => 'All-Around Tumbler with press-in lid. Perfect for coffee shop visits. Fits car cupholders. Keeps drinks cold 24 hours.', 'condition' => 'new', 'price' => 385000.00, 'weight' => 270, 'stock' => 40],
            ['id' => 49, 'store_id' => 1, 'product_category_id' => 2, 'name' => 'Hydro Flask 40oz Wide Mouth with Straw Lid', 'slug' => 'hydroflask-40oz-straw-lid', 'description' => 'Extra large capacity for all-day hydration. Wide mouth for ice cubes. Straw lid for easy sipping. Available in vibrant colors.', 'condition' => 'new', 'price' => 525000.00, 'weight' => 420, 'stock' => 17],
            ['id' => 50, 'store_id' => 2, 'product_category_id' => 2, 'name' => 'Hydro Flask 12oz Coffee Mug', 'slug' => 'hydroflask-12oz-coffee-mug', 'description' => 'True coffee mug experience with insulation. Flex Sip lid with comfortable lip. Easy grip handle. Keeps coffee hot for 6 hours.', 'condition' => 'new', 'price' => 375000.00, 'weight' => 240, 'stock' => 35],

            ['id' => 51, 'store_id' => 1, 'product_category_id' => 3, 'name' => 'Stanley Quencher H2.0 FlowState Tumbler 40oz', 'slug' => 'stanley-quencher-40oz', 'description' => 'Viral sensation! Advanced FlowState lid with rotating cover. Comfort-grip handle. Car cupholder compatible. Reusable straw included.', 'condition' => 'new', 'price' => 485000.00, 'weight' => 400, 'stock' => 45],
            ['id' => 52, 'store_id' => 1, 'product_category_id' => 3, 'name' => 'Stanley Classic Trigger Action Travel Mug 16oz', 'slug' => 'stanley-classic-16oz-mug', 'description' => 'One-hand push button operation. Leak-proof lid. Vacuum insulation keeps drinks hot 7 hours, cold 7 hours. Built-in tea infuser.', 'condition' => 'new', 'price' => 395000.00, 'weight' => 280, 'stock' => 30],
            ['id' => 53, 'store_id' => 2, 'product_category_id' => 3, 'name' => 'Stanley Adventure Quencher 30oz', 'slug' => 'stanley-adventure-30oz', 'description' => 'Rugged outdoor design with built-in handle. Double-wall vacuum insulation. BPA-free. Fits most car cupholders perfectly.', 'condition' => 'new', 'price' => 445000.00, 'weight' => 350, 'stock' => 25],
            ['id' => 54, 'store_id' => 2, 'product_category_id' => 3, 'name' => 'Stanley IceFlow Flip Straw Tumbler 20oz', 'slug' => 'stanley-iceflow-20oz', 'description' => 'Flip straw for easy sipping. Double-wall vacuum insulation. Leak-resistant. Fits under most coffee machines. Dishwasher safe.', 'condition' => 'new', 'price' => 365000.00, 'weight' => 260, 'stock' => 38],
            ['id' => 55, 'store_id' => 1, 'product_category_id' => 3, 'name' => 'Stanley Classic Legendary Bottle 1.1QT', 'slug' => 'stanley-classic-bottle-1qt', 'description' => 'Iconic design since 1913. Keeps drinks hot 32 hours, cold 32 hours. Naturally BPA-free. Lifetime warranty.', 'condition' => 'new', 'price' => 625000.00, 'weight' => 480, 'stock' => 15],

            ['id' => 56, 'store_id' => 2, 'product_category_id' => 4, 'name' => 'Contigo AUTOSEAL West Loop Travel Mug 16oz', 'slug' => 'contigo-autoseal-16oz', 'description' => 'AUTOSEAL technology is leak and spill proof. One-handed drinking. Thermalock vacuum insulation. Fits car cupholders.', 'condition' => 'new', 'price' => 325000.00, 'weight' => 240, 'stock' => 42],
            ['id' => 57, 'store_id' => 2, 'product_category_id' => 4, 'name' => 'Contigo SnapSeal Byron Stainless Steel 20oz', 'slug' => 'contigo-snapseal-20oz', 'description' => 'Leak-proof lid with button-lock. THERMALOCK keeps cold 28 hours. Wide mouth for ice. Top-rack dishwasher safe.', 'condition' => 'new', 'price' => 355000.00, 'weight' => 280, 'stock' => 35],
            ['id' => 58, 'store_id' => 1, 'product_category_id' => 4, 'name' => 'Contigo Luxe AUTOSEAL Vacuum Tumbler 16oz', 'slug' => 'contigo-luxe-16oz', 'description' => 'Premium stainless steel finish. AUTOSEAL spill-proof lid. Slim design fits most cupholders. Keeps hot 5 hours, cold 12 hours.', 'condition' => 'new', 'price' => 295000.00, 'weight' => 220, 'stock' => 45],
            ['id' => 59, 'store_id' => 1, 'product_category_id' => 4, 'name' => 'Contigo Jackson Reusable Water Bottle 24oz', 'slug' => 'contigo-jackson-24oz', 'description' => 'AUTOPOP lid with push button. Leak-proof when closed. Integrated carry handle. BPA-free. Easy clean lid.', 'condition' => 'new', 'price' => 285000.00, 'weight' => 200, 'stock' => 50],
            ['id' => 60, 'store_id' => 2, 'product_category_id' => 4, 'name' => 'Contigo Pinnacle Thermal Bottle 20oz', 'slug' => 'contigo-pinnacle-20oz', 'description' => 'THERMALOCK vacuum insulation. Sports-inspired design. Quick-twist lid. Comfortable angled spout. Sweat-proof exterior.', 'condition' => 'new', 'price' => 315000.00, 'weight' => 260, 'stock' => 38],

            ['id' => 61, 'store_id' => 1, 'product_category_id' => 5, 'name' => 'Klean Kanteen Classic 27oz Wide Mouth', 'slug' => 'klean-kanteen-27oz-wide', 'description' => 'Certified B-Corp. Climate Lock double-wall insulation. 18/8 food-grade stainless steel. Chip-resistant Klean Coat. Plastic-free.', 'condition' => 'new', 'price' => 415000.00, 'weight' => 310, 'stock' => 27],
            ['id' => 62, 'store_id' => 1, 'product_category_id' => 5, 'name' => 'Klean Kanteen TKWide 20oz with Café Cap', 'slug' => 'klean-kanteen-tkwide-20oz', 'description' => 'TKWide design fits ice perfectly. Café Cap for drinking or pouring. Keeps hot 10 hours, iced 50 hours. 100% recyclable.', 'condition' => 'new', 'price' => 385000.00, 'weight' => 280, 'stock' => 31],
            ['id' => 63, 'store_id' => 2, 'product_category_id' => 5, 'name' => 'Klean Kanteen Insulated TKPro 25oz', 'slug' => 'klean-kanteen-tkpro-25oz', 'description' => 'Pro-grade performance. 360° pour-through cap. Keeps hot 30 hours, iced 120 hours. Leakproof. Climate neutral certified.', 'condition' => 'new', 'price' => 525000.00, 'weight' => 390, 'stock' => 20],
            ['id' => 64, 'store_id' => 2, 'product_category_id' => 5, 'name' => 'Klean Kanteen Kid Kanteen 12oz', 'slug' => 'klean-kanteen-kid-12oz', 'description' => 'Perfect size for kids. Leak-proof sport cap. BPA-free. Lightweight. Durable 18/8 stainless steel. Fun colors.', 'condition' => 'new', 'price' => 295000.00, 'weight' => 180, 'stock' => 40],
            ['id' => 65, 'store_id' => 1, 'product_category_id' => 5, 'name' => 'Klean Kanteen Rise 16oz Coffee Tumbler', 'slug' => 'klean-kanteen-rise-16oz', 'description' => 'Chip-resistant powder coat. Splash-proof lid. Fits under coffee machines. Climate Lock insulation. Plastic-free and recyclable.', 'condition' => 'new', 'price' => 345000.00, 'weight' => 240, 'stock' => 34],

            ['id' => 66, 'store_id' => 2, 'product_category_id' => 6, 'name' => 'Thermos Stainless King 24oz Drink Bottle', 'slug' => 'thermos-king-24oz', 'description' => 'Maximum temperature retention. Keeps hot 24 hours, cold 24 hours. Durable stainless steel interior. Twist and pour stopper.', 'condition' => 'new', 'price' => 385000.00, 'weight' => 320, 'stock' => 30],
            ['id' => 67, 'store_id' => 2, 'product_category_id' => 6, 'name' => 'Thermos Guardian 18oz Hard Plastic Bottle', 'slug' => 'thermos-guardian-18oz', 'description' => 'Lightweight Tritan plastic. Leak-proof lid. Hygienic push button. Cool to touch exterior. BPA-free. Budget-friendly.', 'condition' => 'new', 'price' => 185000.00, 'weight' => 150, 'stock' => 55],
            ['id' => 68, 'store_id' => 1, 'product_category_id' => 6, 'name' => 'Thermos Sipp 16oz Vacuum Insulated Travel Mug', 'slug' => 'thermos-sipp-16oz', 'description' => 'Drink-through lid with Eastman Tritan. One-handed operation. Leak-proof. Keeps hot 5 hours, cold 9 hours. Fits cupholders.', 'condition' => 'new', 'price' => 275000.00, 'weight' => 230, 'stock' => 40],
            ['id' => 69, 'store_id' => 1, 'product_category_id' => 6, 'name' => 'Thermos FUNtainer 12oz Bottle', 'slug' => 'thermos-funtainer-12oz', 'description' => 'Colorful design for kids. Keeps cold 12 hours. Durable stainless steel. Hygienic push button. Easy to clean. BPA-free.', 'condition' => 'new', 'price' => 245000.00, 'weight' => 190, 'stock' => 44],
            ['id' => 70, 'store_id' => 2, 'product_category_id' => 6, 'name' => 'Thermos Element5 20oz Backpack Bottle', 'slug' => 'thermos-element5-20oz', 'description' => 'Built-in carry handle. Protective bumper base. Leak-proof lid. Double-wall insulation. Slim design for backpacks.', 'condition' => 'new', 'price' => 325000.00, 'weight' => 270, 'stock' => 35],

            ['id' => 71, 'store_id' => 1, 'product_category_id' => 7, 'name' => 'S\'well Stone Collection 17oz Water Bottle', 'slug' => 'swell-stone-17oz', 'description' => 'Designer marble pattern. Triple-layered insulation. Condensation-free. Keeps cold 36 hours, hot 18 hours. Fashion statement.', 'condition' => 'new', 'price' => 685000.00, 'weight' => 330, 'stock' => 15],
            ['id' => 72, 'store_id' => 1, 'product_category_id' => 7, 'name' => 'S\'well Traveler 20oz Mug', 'slug' => 'swell-traveler-20oz', 'description' => 'Sophisticated design with handle. Splash-proof lid. Wide mouth opening. Premium finish. Perfect for coffee lovers.', 'condition' => 'new', 'price' => 625000.00, 'weight' => 310, 'stock' => 18],
            ['id' => 73, 'store_id' => 2, 'product_category_id' => 7, 'name' => 'S\'well Original 25oz Bottle', 'slug' => 'swell-original-25oz', 'description' => 'Iconic S\'well shape. Museum-quality craftsmanship. Copper-plated interior. BPA/BPS-free. Limited edition patterns.', 'condition' => 'new', 'price' => 725000.00, 'weight' => 350, 'stock' => 11],
            ['id' => 74, 'store_id' => 2, 'product_category_id' => 7, 'name' => 'S\'well Roamer 40oz Bottle', 'slug' => 'swell-roamer-40oz', 'description' => 'Extra large capacity. Built-in handle. Wide mouth for ice. Premium triple-wall insulation. Status symbol bottle.', 'condition' => 'new', 'price' => 885000.00, 'weight' => 450, 'stock' => 10],
            ['id' => 75, 'store_id' => 1, 'product_category_id' => 7, 'name' => 'S\'well Tumbler 18oz with Lid', 'slug' => 'swell-tumbler-18oz', 'description' => 'Stemless wine tumbler design. Sliding lid included. Elegant metallic finish. Vacuum insulated. Perfect for events.', 'condition' => 'new', 'price' => 565000.00, 'weight' => 280, 'stock' => 20],

            ['id' => 76, 'store_id' => 2, 'product_category_id' => 8, 'name' => 'Zojirushi SM-SA48 Stainless Mug 16oz', 'slug' => 'zojirushi-sm-sa48-16oz', 'description' => 'Japanese precision engineering. SlickSteel interior resists odors. Keeps hot 6 hours, cold 17 hours. Compact and lightweight.', 'condition' => 'new', 'price' => 595000.00, 'weight' => 250, 'stock' => 22],
            ['id' => 77, 'store_id' => 2, 'product_category_id' => 8, 'name' => 'Zojirushi SM-KHE48 Stainless Mug 16oz', 'slug' => 'zojirushi-sm-khe48-16oz', 'description' => 'Safety lock prevents spills. One-touch open/close. Wide opening for ice. Nonstick interior. Tight-fitted lid.', 'condition' => 'new', 'price' => 625000.00, 'weight' => 260, 'stock' => 20],
            ['id' => 78, 'store_id' => 1, 'product_category_id' => 8, 'name' => 'Zojirushi SF-CC13 Food Jar 13oz', 'slug' => 'zojirushi-food-jar-13oz', 'description' => 'Not just drinks! Keeps food hot or cold. Wide mouth opening. Compact design. Perfect for soup or yogurt. Superior insulation.', 'condition' => 'new', 'price' => 485000.00, 'weight' => 300, 'stock' => 25],
            ['id' => 79, 'store_id' => 1, 'product_category_id' => 8, 'name' => 'Zojirushi SM-SC48 Stainless Mug 16oz', 'slug' => 'zojirushi-sm-sc48-16oz', 'description' => 'Ultra-slim design fits bags easily. Flip-open lid with safety lock. SlickSteel interior. Vacuum insulated. Made in Japan quality.', 'condition' => 'new', 'price' => 565000.00, 'weight' => 240, 'stock' => 28],
            ['id' => 80, 'store_id' => 2, 'product_category_id' => 8, 'name' => 'Zojirushi SJ-JS10 Stainless Food Jar 10oz', 'slug' => 'zojirushi-food-jar-10oz', 'description' => 'Compact food jar with spoon. Keeps food fresh. Easy to clean nonstick interior. Durable construction. Perfect lunch companion.', 'condition' => 'new', 'price' => 425000.00, 'weight' => 280, 'stock' => 30],

            ['id' => 81, 'store_id' => 3, 'product_category_id' => 9, 'name' => 'Tupperware Australia', 'slug' => 'tupperware-australia-v8YfX', 'description' => 'sangat kokoh pokoknya', 'condition' => 'new', 'price' => 150000.00, 'weight' => 500, 'stock' => 79],
            ['id' => 82, 'store_id' => 3, 'product_category_id' => 9, 'name' => 'Tupperware Universal', 'slug' => 'tupperware-universal-tQdQu', 'description' => 'paling keren deh', 'condition' => 'new', 'price' => 20000000.00, 'weight' => 52, 'stock' => 3],
            ['id' => 83, 'store_id' => 3, 'product_category_id' => 9, 'name' => 'Tupperware Hello Kitty', 'slug' => 'tupperware-hello-kitty-NGRhF', 'description' => 'gambarnya helo kiti', 'condition' => 'new', 'price' => 250000.00, 'weight' => 17, 'stock' => 96],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['id' => $product['id']],
                $product
            );
        }
    }
}